/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";
import { Route as RawIndexImport } from "./routes/raw/index";
import { Route as HomeIndexImport } from "./routes/home/index";
import { Route as DashboardIndexImport } from "./routes/dashboard/index";

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute
} as any);

const RawIndexRoute = RawIndexImport.update({
  id: "/raw/",
  path: "/raw/",
  getParentRoute: () => rootRoute
} as any);

const HomeIndexRoute = HomeIndexImport.update({
  id: "/home/",
  path: "/home/",
  getParentRoute: () => rootRoute
} as any);

const DashboardIndexRoute = DashboardIndexImport.update({
  id: "/dashboard/",
  path: "/dashboard/",
  getParentRoute: () => rootRoute
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/dashboard/": {
      id: "/dashboard/";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/home/": {
      id: "/home/";
      path: "/home";
      fullPath: "/home";
      preLoaderRoute: typeof HomeIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/raw/": {
      id: "/raw/";
      path: "/raw";
      fullPath: "/raw";
      preLoaderRoute: typeof RawIndexImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardIndexRoute;
  "/home": typeof HomeIndexRoute;
  "/raw": typeof RawIndexRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardIndexRoute;
  "/home": typeof HomeIndexRoute;
  "/raw": typeof RawIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/dashboard/": typeof DashboardIndexRoute;
  "/home/": typeof HomeIndexRoute;
  "/raw/": typeof RawIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/dashboard" | "/home" | "/raw";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/dashboard" | "/home" | "/raw";
  id: "__root__" | "/" | "/dashboard/" | "/home/" | "/raw/";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DashboardIndexRoute: typeof DashboardIndexRoute;
  HomeIndexRoute: typeof HomeIndexRoute;
  RawIndexRoute: typeof RawIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  RawIndexRoute: RawIndexRoute
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard/",
        "/home/",
        "/raw/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    },
    "/home/": {
      "filePath": "home/index.tsx"
    },
    "/raw/": {
      "filePath": "raw/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
